// <auto-generated />
using System;
using GestionHospitalisation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionHospitalisation.Migrations
{
    [DbContext(typeof(GestionHospitalisationContext))]
    [Migration("20250424183616_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionHospitalisation.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Compte");
                });

            modelBuilder.Entity("GestionHospitalisation.Models.Hospitalisation", b =>
                {
                    b.Property<int>("NumServ")
                        .HasColumnType("int");

                    b.Property<int>("CodePat")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSortie")
                        .HasColumnType("datetime2");

                    b.Property<double>("Frais")
                        .HasColumnType("float");

                    b.HasKey("NumServ", "CodePat", "DateEntree");

                    b.ToTable("Hospitalisation");
                });

            modelBuilder.Entity("GestionHospitalisation.Models.Patient", b =>
                {
                    b.Property<int>("CodePat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodePat"));

                    b.Property<DateTime>("DateNaiss")
                        .HasMaxLength(100)
                        .HasColumnType("datetime2");

                    b.Property<string>("Mutuelle")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CodePat");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("GestionHospitalisation.Models.Service", b =>
                {
                    b.Property<int>("NumServ")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumServ"));

                    b.Property<string>("LibServ")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("NumServ");

                    b.ToTable("Service");
                });
#pragma warning restore 612, 618
        }
    }
}
